spring:
  application:
    name: notification-service
  jackson:
    deserialization:
      fail-on-null-for-primitives: false
  data:
    mongodb:
      database: ${MONGO_DATABASE:notification}
      uri: ${MONGO_URI:mongodb://gakins:E5press0@localhost:27017/notification}?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000
      auto-index-creation: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OKTA_ISSUER:https://dev-madie.okta.com/oauth2/default}

server:
  port: 8090
  servlet:
    context-path: /api

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: ${LOG_LEVEL:INFO}
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %mdc %-5level %logger{36}.%M - %msg%n"
