spring:
  application:
    name: notification-service
  jackson:
    deserialization:
      fail-on-null-for-primitives: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OKTA_ISSUER:https://dev-madie.okta.com/oauth2/default}
  data:
    mongodb:
      database: ${MONGO_DATABASE:notification}
      # Docker Mongo (madie-mongo container)
      uri: ${MONGO_URI:mongodb://gakins:E5press0@localhost:27017/notification}?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000
      # Local Mongo (no auth)
#      uri: ${MONGO_URI:mongodb://localhost:27017/notification}?authSource=admin&maxPoolSize=50&connectTimeoutMS=2000&serverSelectionTimeoutMS=2000

server:
  port: 8090
  servlet:
    context-path: /api

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

madie:
  user-service:
    base-url: ${USER_SERVICE_BASE_URL:http://localhost:8088}

logging:
  level:
    root: ${LOG_LEVEL:INFO}
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%thread] %mdc %-5level %logger{36}.%M - %msg%n"
